function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, cross_section, luminosity, numPts)
%function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, numPts, cross_section, luminosity)
%Plots the RoC curve for a given dataset.
%Input Parameters are:
%   out_signal     -> The output generated by your detection system when
%                     electrons were applied to it.
%   out_noise      -> The output generated by your detection system when
%                     jets were applied to it
%   cross_section  -> (opt) The cross section of your jets dataset.
%   luminosity     -> (opt) The luminosity you are working with.
%   numPts         -> (opt) The number of points to generate your ROC.
%
%If no output parameters are specified, then the ROC is plot. Otherwise,
%the sp values, cut values, the detection efficiency and false alarm rate 
% are returned.
%

if nargin == 2,
    numPts = 1000;
    cross_section = 0.191;
    luminosity = 10^31;
end

if nargin == 3,
    numPts = 1000;
    luminosity = 10^31;
end

if nargin == 4,
    numPts = 1000;
end

nSignal = length(out_signal);
nNoise = length(out_noise);

cutVec = -1 : (2/numPts) : 1;
detVec = zeros(1,length(cutVec));
faVec = zeros(1,length(cutVec));

for i=1:length(cutVec),
    [detVec(i), faVec(i)] = getEff(out_signal, out_noise, cutVec(i));
end

spVec = calcSP(detVec, faVec);
[sp, cutIdx] = max(spVec);
cut = cutVec(cutIdx);

detVec = 100*detVec;
faVec = 100*faVec;
%faVec = (cross_section*luminosity) * faVec;

if nargout ~= 4,
    plot(faVec, detVec);
    hold on
    plot(faVec(cutIdx), detVec(cutIdx), 'rx');
    title('ROC Analysis');
    xlabel('Jet Rate');
    ylabel('Electron Efficiency');
    legend('ROC', 'Max SP');
    hold off;
end
