function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, numPts)
%function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, numPts)
%Plots the RoC curve for a given dataset.
%Input Parameters are:
%   out_signal     -> The output generated by your detection system when
%                     electrons were applied to it.
%   out_noise      -> The output generated by your detection system when
%                     jets were applied to it
%   numPts         -> (opt) The number of points to generate your ROC.
%
%If no output parameters are specified, then the ROC is plot. Otherwise,
%the sp values, cut values, the detection efficiency and false alarm rate 
% are returned.
%

if nargin == 2,
    numPts = 1000;
end

cutVec = -1 : (2/numPts) : 1;
detVec = zeros(1,length(cutVec));
faVec = zeros(1,length(cutVec));

for i=1:length(cutVec),
    [detVec(i), faVec(i)] = getEff(out_signal, out_noise, cutVec(i));
end

spVec = calcSP([detVec; (1-faVec)]);
[sp, cutIdx] = max(spVec);
cut = cutVec(cutIdx);

if nargout ~= 4,
    plot(100*faVec, 100*detVec);
    hold on
    plot(faVec(cutIdx), detVec(cutIdx), 'rx');
    title('ROC Analysis');
    xlabel('False Alarm Probability (%)');
    ylabel('Signal Detection Efficiency (%)');
    legend('ROC', 'Max SP');
    hold off;
end
