function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, numPts)
%function [spVec, cutVec, detVec, faVec] = genROC(out_signal, out_noise, numPts)
%Plots the RoC curve for a given dataset.
%Input Parameters are:
%   out_signal     -> The output generated by your detection system when
%                     electrons were applied to it.
%   out_noise      -> The output generated by your detection system when
%                     jets were applied to it
%   numPts         -> (opt) The number of points to generate your ROC.
%
%If any output parameters is specified, then the ROC is plot. Otherwise,
%the sp values, cut values, the detection efficiency and false alarm rate 
% are returned (in that order).
%

if nargin < 3, numPts = 1000; end

%Placing the data within the [-1,+1] range.
[aux, pp] = mapminmax([out_signal out_noise]);
clear aux;
out_signal = mapminmax('apply', out_signal, pp);
out_noise = mapminmax('apply', out_noise, pp);

%Stablishing where to calculate the efficiencies (thresholds).
cutVec = -1 : (2/numPts) : 1;
cutVec = cutVec(1:numPts);
detVec = zeros(1,length(cutVec));
faVec = zeros(1,length(cutVec));

for i=1:length(cutVec),
    [detVec(i), faVec(i)] = getEff(out_signal, out_noise, cutVec(i));
end

spVec = calcSP([detVec; (1-faVec)]);
[sp, cutIdx] = max(spVec);

if nargout == 0,
    plot(100*faVec, 100*detVec);
    hold on
    plot(100*faVec(cutIdx), 100*detVec(cutIdx), 'rx');
    title('ROC Analysis');
    xlabel('False Alarm Probability (%)');
    ylabel('Signal Detection Efficiency (%)');
    legend('ROC', 'Max SP');
    hold off;
end

%Sinde we normalize the output values to be within +- 1, the vector of
%thresholds shoube be, at the end of this function, with the same dnamic
%range as the original output values (non-normalized).
cutVec = mapminmax('reverse', cutVec, pp);
