%function out = nsim(net, in_data)
%Propagates a input data set through a neural network, returning the output generated for
% each input, just like sim.
%Parameters are:
%	net             -> The neural network structure created by "newff2".
%	in_data         -> The input data.
%The function returns:
%	out -> The output generated by the network for each input.
%