function out = nsim(net, in_data)
%function out = nsim(net, in_data)
%Propagates a input data set through a neural network, returning the output generated for
% each input, just like sim. input_data can be a standard matrix, or a cell
% vector. If it is a cell vector, the feedforward is applyed for each cell,
%and the output will be, also, a cell vector.
%Parameters are:
%	net             -> The neural network structure created by "newff2".
%	in_data         -> The input data.
%The function returns:
%	out -> The output generated by the network for each input.
%

if iscell(in_data),
  nClasses = length(in_data);
  out = cell(1, nClasses);
  for i=1:nClasses,
    out{i} = sim_c(net, in_data{i});
  end
else
  out = sim_c(net, in_data);
end
